[2021-10-18 17:19:39,115] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2021-10-17T00:00:00+00:00 [queued]>
[2021-10-18 17:19:39,121] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2021-10-17T00:00:00+00:00 [queued]>
[2021-10-18 17:19:39,122] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-10-18 17:19:39,122] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-10-18 17:19:39,122] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-10-18 17:19:39,140] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2021-10-17T00:00:00+00:00
[2021-10-18 17:19:39,141] {standard_task_runner.py:52} INFO - Started process 5151 to run task
[2021-10-18 17:19:39,146] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2021-10-17T00:00:00+00:00', '--job-id', '51', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpzo8bhfv7', '--error-file', '/tmp/tmppoq4mjew']
[2021-10-18 17:19:39,147] {standard_task_runner.py:77} INFO - Job 51: Subtask task_3
[2021-10-18 17:19:39,247] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2021-10-17T00:00:00+00:00 [running]> on host airflowvm
[2021-10-18 17:19:39,349] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2021-10-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-17T00:00:00+00:00
[2021-10-18 17:19:39,350] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-10-18 17:19:39,350] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-10-18 17:19:39,353] {subprocess.py:75} INFO - Output:
[2021-10-18 17:19:42,356] {subprocess.py:83} INFO - Command exited with return code 0
[2021-10-18 17:19:42,401] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20211017T000000, start_date=20211018T171939, end_date=20211018T171942
[2021-10-18 17:19:42,444] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-18 17:19:42,480] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-18 17:51:19,980] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2021-10-17T00:00:00+00:00 [queued]>
[2021-10-18 17:51:19,999] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2021-10-17T00:00:00+00:00 [queued]>
[2021-10-18 17:51:19,999] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-10-18 17:51:20,000] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-10-18 17:51:20,000] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-10-18 17:51:20,031] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2021-10-17T00:00:00+00:00
[2021-10-18 17:51:20,033] {standard_task_runner.py:52} INFO - Started process 14268 to run task
[2021-10-18 17:51:20,055] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2021-10-17T00:00:00+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpgil1exa3', '--error-file', '/tmp/tmpcj3eqecy']
[2021-10-18 17:51:20,056] {standard_task_runner.py:77} INFO - Job 3: Subtask task_3
[2021-10-18 17:51:20,730] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2021-10-17T00:00:00+00:00 [running]> on host airflowvm
[2021-10-18 17:51:20,933] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2021-10-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-17T00:00:00+00:00
[2021-10-18 17:51:20,934] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-10-18 17:51:20,934] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-10-18 17:51:20,944] {subprocess.py:75} INFO - Output:
[2021-10-18 17:51:23,948] {subprocess.py:83} INFO - Command exited with return code 0
[2021-10-18 17:51:24,031] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20211017T000000, start_date=20211018T175119, end_date=20211018T175124
[2021-10-18 17:51:24,094] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-18 17:51:24,103] {local_task_job.py:151} INFO - Task exited with return code 0
